apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn
            values:
            - gpu
      # preferredDuringSchedulingIgnoredDuringExecution: #from here not mentioned in session, own example tried
      # - weight: 1
      #   preference:
      #     matchExpressions:
      #     - key: hardware
      #       operator: NotIn
      #       values:
      #       # - gpu
      #       - gpu
  containers:
  - name: nginx
    image: nginx
